Removed obsolete x-pack plugin removal instruction
x-pack isn't bundled with ES anymore and doesn't need removing.  
Also wasn't available at that bin/ location
---
root@vsf-main:~# /usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack --purge
-> removing [x-pack]...
ERROR: plugin [x-pack] not found; run 'elasticsearch-plugin list' to get list of installed plugins
root@vsf-main:~# /usr/share/elasticsearch/bin/elasticsearch-plugin list
root@vsf-main:~#